name: pr

on:
  pull_request:
    branches:
      - "**"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.11.9", "3.11.x"]
        poetry-version: ["1.8.3"]
      fail-fast: false

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Setup Dependencies
        id: setup-dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-venv
          sudo apt-get install curl build-essential gfortran libblas-dev libffi-dev liblapack-dev libopenblas-dev libportaudio2 libssl-dev portaudio19-dev
          pip install --upgrade pip setuptools wheel
          pip install llvmlite scipy
          pip install --no-cache-dir pyaudio==0.2.14
      - name: Set up Rust
        id: setup-rust
        uses: linkerd/dev/actions/setup-rust@v42
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install Poetry
        uses: snok/install-poetry@v1.3.4
        with:
          version: ${{ matrix.poetry-version }}
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ matrix.poetry-version }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root
      - name: Install library
        run: poetry install --no-interaction
      - name: Run application
        run: poetry run application
      - name: Test with pytest
        run: poetry run pytest tests --cov=myapplication

  build-image:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
